version: "3"

services:
  filebrowser:
    image: hurlenko/filebrowser
   # user: "bob:root"
    container_name: filebrowser
    ports:
      - 8080
    volumes:
      - /raid/dockerapps/filebrowser/data:/data
      - /raid/dockerapps/filebrowser:/config
    environment:
      - files.example.com=/filebrowser
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.filebrowser.rule=Host(`${TRAEFIK_FILEBROWSER}`)"
      - "traefik.http.routers.filebrowswer.entrypoints=https"
      - "traefik.http.routers.filebrowser.tls=true"
      - "traefik.http.routers.filebrowser.tls.certresolver=mydnschallenge"
     # - "traefik.http.routers.filebrowser.service=filebrowser"
     # - "traefik.http.services.filebrowser.loadbalancer.server.port=8080"

      # Watchtower Update
      - "com.centurylinklabs.watchtower.enable=true"

networks:
  proxy:
    external: true
