version: "3"

services:
  gotify:
    image: gotify/server-arm64
    container_name: gotify
    restart: unless-stopped
   # ports:
   #   - "8080:80"
    volumes:
   #   - "./data:/gotify-app"
      - "./data:/app/data"
    environment:
      - GOTIFY_DEFAULTUSER_PASS=${GOTIFY_DEFAULTUSER_PASS}
   #   - TZ=${TIME_ZONE}
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gotify.rule=Host(`${TRAEFIK_GOTIFY}`)"
      - "traefik.http.routers.gotify.entrypoints=https"
      - "traefik.http.routers.gotify.tls=true"
      - "traefik.http.routers.gotify.tls.certresolver=mydnschallenge"

      # Watchtower Update
      - "com.centurylinklabs.watchtower.enable=true"

networks:
  proxy:
    external: true
